# directory of the dataset
dataset: '/home/shangzhouye/Documents/slam/data_odometry_gray/dataset/sequences/00/'

# whether write the pose to txt file or not
if_write_pose: false

# whether use rviz visualization or not
if_rviz: true